﻿services:
  money-guardian-api:
    image: jeymikuz/mg-api:latest
    build:
      context: .
      dockerfile: src/money.guardian.api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=mg_main
    ports:
      - 5000:80

  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  money-guardian-frontend:
    image: jeymikuz/mg-frontend:latest
    build:
      context: .
      dockerfile: src/money.guardian.frontend/Dockefile
    volumes:
      - /var/lib/web/data
    environment:
      - NEXTAUTH_SECRET=somethinfsedafdsfdasf
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - API_URL=http://money-guardian-api/api/v1/
    ports:
      - 3000:3000

volumes:
  pgdata: